# Generated by Django 4.0.3 on 2022-03-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
