# Generated by Django 4.0.3 on 2022-03-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_date_accepted_to_sand_privacy_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
