# Generated by Django 4.0.3 on 2022-03-12 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_weather_monitoring_is_on_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
