# Generated by Django 4.0.3 on 2022-03-13 06:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 6, 7, 49, 838094, tzinfo=utc)),
        ),
    ]
